version: '3.3'
services:
  db:
    image: influxdb:1.7.10-alpine
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
  scraper:
    build: scraper
