version: '3.3'
services:
  sqldb:
    image: mariadb
    volumes:
        - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
        # - ./mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  influxdb:
    image: influxdb:1.7.10-alpine
    volumes:
      - ./influxdb/initdb.d:/docker-entrypoint-initdb.d
      # - ./influxdb/data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    ports:
      - $PORT:3000
    depends_on:
      - influxdb
      - sqldb

  scraper:
    build: scraper
    depends_on:
      - sqldb
      - influxdb
