apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    orgId: 1
    url: http://influxdb:8086
    user: root
    database: ebay
    isDefault: false
    editable: true
    version: 1
    secureJsonData:
      password: root

  - name: mariadb
    type: mysql
    orgId: 1
    url: sqldb:3306
    user: root
    database: ebay
    isDefault: false
    editable: true
    version: 1
    secureJsonData:
      password: root

  - name: influxdb-Flux
    type: influxdb
    orgId: 1
    url: http://influxdb:8086
    access: proxy
    editable: true
    secureJsonData:
      token: "root:root"
    jsonData:
      version: Flux
      organization: "yamada"
      defaultBucket: ebay
